name: Deploy MkDocs

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Get Python version checksum
        id: python-version-checksum
        shell: bash
        run: |
          VERSION_SHA256SUM=$(python --version --version | sha256sum | cut -d ' ' -f 1)
          echo "VERSION_SHA256SUM=$VERSION_SHA256SUM"
          echo "version-sha256sum=$VERSION_SHA256SUM" >> "$GITHUB_OUTPUT"

      - name: Get UV version checksum
        id: uv-version-checksum
        shell: bash
        run: |
          VERSION_SHA256SUM=$(uv --version | sha256sum | cut -d ' ' -f 1)
          echo "VERSION_SHA256SUM=$VERSION_SHA256SUM"
          echo "version-sha256sum=$VERSION_SHA256SUM" >> "$GITHUB_OUTPUT"

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: >-
            venv|
            ${{ runner.os }}|
            pre-commit|
            ${{ steps.python-version-checksum.outputs.version-sha256sum }}|
            ${{ steps.uv-version-checksum.outputs.version-sha256sum }}|
            ${{ hashFiles('**/uv.lock') }}

      - name: Install Dependencies
        run: |
          uv sync --group docs

      - name: Build MkDocs site
        run: uv run mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
